#!/usr/bin/env perl

use File::Basename;

my $RSV_VERSION = "3.4.2";

my $dir = dirname($0);
my @lines = `svn status --show-updates $dir 2>&1`;
# Ignore lines that begin with '?' or 'Status against revision:'                                            
my @bad = grep !/^(\?|Status against revision:)/, @lines;
if(@bad) {
    print "Subversion checkout is not up-to-date\n";
    print "Lines:\n";
    print "@bad";
    exit 1;
}


# Form the tarballs
system("cp -r rsv-metrics rsv-metrics-$RSV_VERSION");
system("tar zcf rsv-metrics-$RSV_VERSION.tar.gz `find rsv-metrics-$RSV_VERSION ! -name \*~ ! -name .#\* ! -type d | grep -v '\.svn'`");
system("rm -fr rsv-metrics-$RSV_VERSION");

system("cp -r rsv-core rsv-core-$RSV_VERSION");
system("perl -pi -e's/\@\@VERSION\@\@/$ENV{RSV_VERSION}/' rsv-core-$RSV_VERSION/lib/python/rsv/rsv-control.py");
system("tar zcf rsv-core-$RSV_VERSION.tar.gz `find rsv-core-$RSV_VERSION ! -name \*~ ! -name .#\* ! -type d | grep -v '\.svn'`");
system("rm -fr rsv-core-$RSV_VERSION");

system("cp -r rsv-consumers rsv-consumers-$RSV_VERSION");
system("tar zcf rsv-consumers-$RSV_VERSION.tar.gz `find rsv-consumers-$RSV_VERSION ! -name \*~ ! -name .#\* ! -type d | grep -v '\.svn'`");
system("rm -fr rsv-consumers-$RSV_VERSION");

my $dir = "/p/vdt/public/html/upstream/$VERSION";
print "Likely installation instructions:\n";
print "mkdir $dir\n";
print "mv *.tar.gz $dir/\n";
