#!/bin/bash

RSV_VERSION=$(python -c "import sys; sys.path.insert(0, 'rsv-core/lib/python'); from rsv import version; sys.stdout.write(version.__version__ + '\n')")

set -o errexit

verify_svn_up_to_date () {
    local dir
    local files
    local up_to_date
    dir=$(dirname $0)
    files=$(svn status --show-updates $dir 2>&1 | egrep -v '(\?|Status against revision:)') || up_to_date=Y
    if [[ $up_to_date != Y ]]; then
        echo Subversion checkout is not up-to-date
        echo Lines:
        echo "$files"
        exit 1
    fi
}

copy_rsv_files () {
    mkdir -p rsv-$RSV_VERSION
    cp -r rsv-consumers rsv-core rsv-metrics rsv-$RSV_VERSION/
}

create_tarball () {
    local files
    files=$(find rsv-$RSV_VERSION \( -name .git -o -name .svn \) -prune -o \( \! -name \*~ \! -name .#\* \! -name .svnignore \! -iname tags \! -type d -print \))
    tar zcf rsv-$RSV_VERSION.tar.gz $files
}

copy_rsv_files_from_git () {
  local commit=${1:-HEAD}
  git archive --prefix=rsv-$RSV_VERSION/ "$commit" \
  | tar x rsv-$RSV_VERSION/rsv-{consumers,core,metrics}
}

print_instructions () {
    local dir
    dir="/p/vdt/public/html/upstream/rsv/$RSV_VERSION"
    echo Likely installation instructions:
    echo "        mkdir $dir"
    echo "        mv rsv-$RSV_VERSION.tar.gz $dir/"
}

cleanup () {
    rm -rf rsv-$RSV_VERSION
}

if [[ $1 = --git ]]; then
  shift
  copy_rsv_files_from_git "$@"
else
  verify_svn_up_to_date
  copy_rsv_files
fi
create_tarball
print_instructions
cleanup

