#!/bin/sh

VERSION=3.3.0beta11

# Form the two tarballs
tar zcf osg-rsv-metrics-$VERSION.tar.gz `find osg-rsv/bin/probes osg-rsv/bin/metrics osg-rsv/CHANGELOG.metrics osg-rsv/etc/metrics osg-rsv/meta/metrics ! -name \*~ ! -name .#\* ! -type d | grep -v '\.svn'`

tar zcf  osg-rsv-core-$VERSION.tar.gz `find osg-rsv/bin/rsv-control osg-rsv/bin/consumers osg-rsv/bin/misc osg-rsv/config osg-rsv/lib osg-rsv/logs osg-rsv/logs/probes osg-rsv/logs/consumers osg-rsv/meta/consumers osg-rsv/etc/*.conf osg-rsv/CHANGELOG.core ! -name \*~ ! -name .#\* ! -type d | grep -v '\.svn'` osg-rsv/etc/consumers osg-rsv/output
