#!/usr/bin/env python

import os
import sys
import glob
import commands
import re

# Verbose should be turned into a command line option
verbose = 0

errors = 0
for probe in glob.glob("osg-rsv/bin/probes/*-probe"):
    bin_dir = os.path.dirname(probe)

    #
    # Check that metafile exists
    #
    meta_file = os.path.join(bin_dir, "meta", os.path.basename(probe) + ".meta")
    if not os.path.exists(meta_file):
        print "Meta file does not exist for probe '" + probe + "'"
        errors += 1

    #
    # Check that metafile contains correct contents
    #
    cmd = "PERL5LIB=%s:$PERL5LIB %s -l -m all" % (bin_dir, probe)
    ret, probe_out = commands.getstatusoutput(cmd)
    if ret:
        print "Command failed: " + cmd
        errors += 1
        continue

    # We added the description manually to the meta files, so we'll strip it out now
    meta_arr = filter(lambda x: not re.match('^description', x), open(meta_file).readlines())
    meta_arr[-1] = meta_arr[-1].rstrip()
    meta_out = ''.join(meta_arr)

    if meta_out != probe_out:
        print "Meta file '" + os.path.basename(probe) + "' is not identical to probe output"
        errors += 1
        if verbose:
            print "-----------"
            print meta_out
            print "-----------"
            print probe_out
            print "-----------"



sys.exit(errors)
