#!/usr/bin/env python
from __future__ import print_function
import sys

print("The gratia-consumer has been removed.  Please disable it by running")
print("    rsv-control --disable gratia-consumer")
print("    rsv-control --off gratia-consumer")
sys.exit(0)
