#!/usr/bin/env perl

###############################################################################
##
##
## Original Author: Anand Padmanabhan
##
## This Perl script tests if the VOMS handshake has occurred
##
##
## REQUIRES
##  'RSVProbeBase
##  'RSVProbeCACert
##
################################################################################

## Perl modules to use
use strict;
use RSVProbeBase;
use RSVProbeCACert;

######## Global variables go here ################################
our %o;         *o         = \%RSVProbeBase::o;
our %metric;    *metric    = \%RSVProbeBase::metric;

################## Local Variables for this probe #####################

&RSVProbeBase::Init();
&RSVProbeBase::Run();



## Main Program ends ##
################################################################################


################################################################################
###### Local Sub routines begin ###########
################################################################################
sub Init {

    &RSVProbeBase::Set_MetricName ("org.osg.verify.voms.handshake");

    ## Pass "status" or "performance" depending on metric type
            
    &RSVProbeBase::Set_MetricType ("status");
    &RSVProbeBase::Set_ServiceType ("OSG-CE");
    &RSVProbeBase::Set_ServiceVersion (">= OSG CE 1.0.0");
    &RSVProbeBase::Set_ProbeType ("OSG-CE");

    ## Should automating tools run this probe on above probeType by default?
    &RSVProbeBase::Set_EnableByDefault ("false");
    
    ## Unix cron type metric interval
    &RSVProbeBase::Set_MetricInterval ("50 */6 * * *");

    ## Define this value from RCS/SVN version
    ## What version of the WLCG specification does this probe conform to?
    &RSVProbeBase::Set_ProbeRevision ('3.0');
    &RSVProbeBase::Set_ProbeSpecVersion ("0.91");

    ## Basic intro for the probe; This string will be used by Print_Usage ()
    &RSVProbeBase::Set_ProbeHelpIntro 
	("IMPORTANT NOTE: This is a site-level probe that checks when edg-mkgridmap was last run.\n\n");
	
    ## Additional options to print in Usage info used by Print_Usage ()
    &RSVProbeBase::Set_ProbeHelpOptions 
    (
    " [--warning-hours <\# hours>]    Number of hours elapsed before warning is to be issued\n".
    " [--error-hours <\# hours>]    Number of hours elapsed before error is to be issued\n".
    " [--worker-script-file <file>     Worker script file to use.".
    " [--local-ce]          The verify test is run on localhost and not through globus gatekeeper."
   );
    
    ## Uncomment if you want additional command line options
    &RSVProbeBase::Extra_CLI_Option ("warning-hours=i","warnHrs");
    &RSVProbeBase::Extra_CLI_Option ("error-hours=i","errorHrs");
    &RSVProbeBase::Extra_CLI_Option ("worker-script-file=s","workerScriptFile");
    &RSVProbeBase::Extra_CLI_Option ("local-ce","localCE");
    
     ## Uncomment if you do not want detailsData to be trimmed to $o{'detailsDataMaxLength}
    &RSVProbeBase::Set_DetailsDataTrim ("False");
}


sub Run {
    ## Get the remote environment variable
    if (! $o{'localCE'}){
        &RSVProbeBase::Get_Remote_Env();
    }

    ## Initialize local variables
    &Initialize_Local();

    ## Real tests begin now - check for expired certs now 
    &RSVProbeCACert::Check_VO_handshake();

    ## Print metric, and we're all done!
    &RSVProbeBase::Print_Metric ();
}

## Initialize local variables
sub Initialize_Local{
    $o{'warnHrs'}  = 1*24 if (! $o{'warnHrs'}) ; ## Warning after24 hrs
    $o{'errorHrs'} = 3*24 if (! $o{'errorHrs'}); ## Error after 72 Hrs
    $o{'workerScriptFile'} = "$o{'PROBE_DIR_LOCAL'}/worker-scripts/edgmkgridmap-lastrun.sh" if (!defined($o{'workerScriptFile'}));
}

## None for now
