#!/bin/sh

dir=`pwd`

if [ ! -w $dir ]; then
    echo "I'm sorry, I don't have permission to create rsv-profile.tar.gz"
    echo "in the current directory. Please change into a directory where"
    echo "you have permission, or switch to a user that does have permission"
    exit 1
fi

if [ "x${VDT_LOCATION}" = "x" ]
then
    echo "VDT_LOCATION is not defined. You need to source setup.sh or "
    echo "setup.csh before you can run the rsv-profiler."
    exit 1
fi

cd $VDT_LOCATION

filedirname=rsv-profiler.files
export rsvfiledir="$dir/$filedirname"
if [ -e $rsvfiledir ]; then
  rm -fr $rsvfiledir
fi
mkdir $rsvfiledir
export rsvlog=$rsvfiledir/rsv-profile.txt
rm -f $rsvlog

echo "OSG-RSV Profiler"
echo "Analyzing..."


##
## Basic stuff
##

echo "OSG-RSV Profile " >> $rsvlog
date                    >> $rsvlog
echo ""                 >> $rsvlog
echo "Hostname:"        >> $rsvlog
/bin/hostname           >> $rsvlog
echo ""                 >> $rsvlog
echo "uname:"           >> $rsvlog
/bin/uname -a           >> $rsvlog
echo ""                 >> $rsvlog
echo "current user:"    >> $rsvlog
/usr/bin/whoami         >> $rsvlog
echo ""                 >> $rsvlog
echo "vdt-version:"     >> $rsvlog
vdt/bin/vdt-version     >> $rsvlog
echo ""                 >> $rsvlog
echo ""                 >> $rsvlog


##
## Condor stuff
##
echo "Condor information" >> $rsvlog

echo "Condor version:" >> $rsvlog
if [ -r condor-cron/wrappers/condor_cron_version ]; then 
  condor-cron/wrappers/condor_cron_version  >> $rsvlog 2>&1
else
  echo "cannot find condor_cron_version"    >> $rsvlog
fi
echo ""                                     >> $rsvlog


echo "condor_cron_q:" >> $rsvlog
if [ -r condor-cron/wrappers/condor_cron_q ]; then 
  condor-cron/wrappers/condor_cron_q  >> $rsvlog 2>&1
else
  echo "cannot find condor_cron_q"    >> $rsvlog
fi
echo ""                               >> $rsvlog

condor_log_dir=`condor-cron/wrappers/condor_cron_config_val log`
echo "Trying to copy condor logs from $condor_log_dir:" >> $rsvlog
if [ -d $condor_log_dir ]; then
  cp -p $condor_log_dir/*Log $rsvfiledir
  echo "copied condor logs"      >> $rsvlog
else
  echo "cannot find condor logs" >> $rsvlog
fi

echo "Trying to copy condor_conf file..." >> $rsvlog
if [ -r condor-cron/etc/condor_config ]; then
  cp condor-cron/etc/condor_config $rsvfiledir
  echo "copied condor_config"      >> $rsvlog
else
  echo "cannot find condor_config" >> $rsvlog
fi

echo "Trying to copy local condor config file..." >> $rsvlog
local_config=`condor-cron/wrappers/condor_cron_config_val LOCAL_CONFIG_FILE`
if [ -r $local_config ]; then
  cp $local_config $rsvfiledir
  echo "copied local config file $local_config"    >> $rsvlog
else
  echo "cannot find local condor-cron config file" >> $rsvlog
fi




##
## RSV stuff
##
echo "" >> $rsvlog
echo "" >> $rsvlog
echo "RSV information" >> $rsvlog
echo "" >> $rsvlog
echo "" >> $rsvlog

echo "rsv-control -l" >> $rsvlog
osg-rsv/bin/rsv-control -l >> $rsvlog 2>&1
echo "" >>$rsvlog

echo "rsv-control -j" >> $rsvlog
osg-rsv/bin/rsv-control -j >> $rsvlog 2>&1
echo "" >>$rsvlog

echo "rsv-control --verify" >> $rsvlog
osg-rsv/bin/rsv-control --verify >> $rsvlog 2>&1
echo "" >>$rsvlog

echo "Trying to copy etc directory..." >> $rsvlog
if [ -e osg-rsv/etc ]; then
  cp -pr osg-rsv/etc/ $rsvfiledir
  echo "copying etc dir"     >> $rsvlog
else
  echo "cannot find etc dir" >> $rsvlog
fi
echo "" >> $rsvlog

# See if there is anything in this directory
echo "Failed gratia directory:" >> $rsvlog
ls osg-rsv/output/failed-gratia-records >> $rsvlog 2>&1
echo "" >> $rsvlog

# Attempt to see if proxy exists
echo "Looking for RSV proxy..." >> $rsvlog
proxy=`grep service-proxy osg-rsv/etc/rsv.conf | perl -e '$t = <STDIN>; if($t =~ /^\s*service-proxy\s*=\s*(\S+)/) { print "$1\n" }'`
if [ "x${proxy}" = "x" ]; then
  proxy=`grep proxy-file osg-rsv/etc/rsv.conf | perl -e '$t = <STDIN>; if($t =~ /^\s*proxy-file\s*=\s*(\S+)/) { print "$1\n" }'`
  if [ "x${proxy}" = "x" ]; then
    echo "Cannot figure out where proxy is.  Will run `ls -l /tmp/x509*` instead." >> $rsvlog
    ls -l /tmp/x509* >> $rsvlog
  else
    echo "Proxy information:" >> $rsvlog
    ls -l $proxy >> $rsvlog
  fi
else
  echo "Proxy information:" >> $rsvlog
  ls -l $proxy >> $rsvlog
fi
echo "" >> $rsvlog

# Get proxy information
id=`id -u`
user=`grep user osg-rsv/etc/rsv.conf | perl -e '$t = <STDIN>; if($t =~ /^\s*user\s*=\s*(\S+)/) { print "$1\n" }'`
if [ ${id} == "0" ]; then
  echo "grid-proxy-info:" >> $rsvlog
  su -c "X509_USER_PROXY=$proxy globus/bin/grid-proxy-info" $user >> $rsvlog 2>&1
else
  echo "Not root, might not be able to run grid-proxy-info but still trying..." >> $rsvlog
  X509_USER_PROXY=$proxy globus/bin/grid-proxy-info >> $rsvlog 2>&1
fi

# Get config.ini
if [ -e osg/etc/config.ini ]; then
  cp osg/etc/config.ini $rsvfiledir
  echo "copying config.ini" >> $rsvlog
else
  echo "could not find config.ini" >> $rsvlog
fi
echo "" >> $rsvlog


# Get some information from the RSV and consumer logs
echo "Getting RSV probe and consumer logs:" >> $rsvlog
mkdir $rsvfiledir/logs
mkdir $rsvfiledir/logs/consumers $rsvfiledir/logs/probes
perl -e 'foreach $file (`ls -1 osg-rsv/logs/probes/`) { chomp($file); system("echo $file >> $ENV{rsvlog}"); system("tail -1000 osg-rsv/logs/probes/$file > $ENV{rsvfiledir}/logs/$file") }'
perl -e 'foreach $file (`ls -1 osg-rsv/logs/consumers/`) { chomp($file); system("echo $file >> $ENV{rsvlog}"); system("tail -1000 osg-rsv/logs/consumers/$file > $ENV{rsvfiledir}/logs/$file") }'
echo "" >> $rsvlog

echo "Done, making tarball" >> $rsvlog

# Make the tarball
echo "Making tarball (rsv-profiler.tar.gz)"
cd $dir
if [ -e rsv-profiler.tar.gz ]; then
  rm rsv-profiler.tar.gz
fi

tar czf rsv-profiler.tar.gz $filedirname
rm -fr $filedirname
