#!/usr/bin/env perl

use strict;
use warnings;
use RSVMetric;

print_output_header();

my %options = process_command_line();

my $cmd;
if (exists($options{htcondor_ce}) && $options{htcondor_ce}) {
    find_binaries("condor_ce_ping");
    $cmd = "condor_ce_ping -pool '$options{u}' -table READ WRITE DAEMON";
}
else {
    find_binaries("globusrun");
    $cmd = "globusrun -a -r '$options{u}'";
}

my $output = `$cmd`;

if($? == 0) {
    print "OK\n";
    print "Output from $cmd:\n";
    print "$output\n";
}
else {
    # The message from globusrun is not generally helpful.  So we will
    # print it, but we'll also try a globus-url-copy and include that
    # output because it tends to have better error messages.
    print "CRITICAL\n";
    print "Output from $cmd\n";
    print "$output\n";

    # TODO Now run globus-url-copy
}

exit 0;
