#!/usr/bin/env perl

use strict;
use warnings;
use Getopt::Long;

use lib qw(/usr/libexec/rsv/probes);
use RSVMetric;

print_output_header();

my $OPT_HOSTNAME;
my $OPT_METRIC;

GetOptions("u=s"        => \$OPT_HOSTNAME,
           "m=s"        => \$OPT_METRIC,
           "help|usage" => \&usage);

my $cmd = "globusrun -a -r $OPT_HOSTNAME";
my $output = `$cmd`;

if($? == 0) {
    print "OK\n";
    print "Output from $cmd:\n";
    print "$output\n";
}
else {
    # The message from globusrun is not generally helpful.  So we will
    # print it, but we'll also try a globus-url-copy and include that
    # output because it tends to have better error messages.
    print "CRITICAL\n";
    print "Output from $cmd\n";
    print "$output\n";

    # TODO Now run globus-url-copy
}

exit 0;

sub usage {
    print STDERR "Usage: $0\n";
    print STDERR "\t-u <hostname>\n";
    print STDERR "\t-m <metric>\n";
    exit 1;
}

