#!/usr/bin/env perl

use strict;
use warnings;
use RSVMetric;

print_output_header();

my $DEFAULT_GATEKEEPER_TYPE = 'gram';

my %options = process_command_line('gatekeeper-type=s' => "Either 'gram' or 'condor-ce'");

my $gatekeeper_type = $DEFAULT_GATEKEEPER_TYPE;
if (defined($options{'gatekeeper-type'})) {
    $gatekeeper_type = lc $options{'gatekeeper-type'};
}

my $cmd;
if ($gatekeeper_type eq 'condor-ce') {
    find_binaries("condor_ce_ping");
    $cmd = "condor_ce_ping -pool '$options{u}' -table READ WRITE DAEMON";
}
elsif ($gatekeeper_type eq 'gram') {
    find_binaries("globusrun");
    $cmd = "globusrun -a -r '$options{u}'";
}
else {
    print STDERR "Invalid gatekeeper-type specified. Must be either 'gram' or 'condor-ce'\n";
    exit 1;
}

my $output = `$cmd`;

if($? == 0) {
    print "OK\n";
    print "Output from $cmd:\n";
    print "$output\n";
}
else {
    # The message from globusrun is not generally helpful.  So we will
    # print it, but we'll also try a globus-url-copy and include that
    # output because it tends to have better error messages.
    print "CRITICAL\n";
    print "Output from $cmd\n";
    print "$output\n";

    # TODO Now run globus-url-copy
}

exit 0;
