#!/usr/bin/env perl

use strict;
use warnings;
use RSVMetric;

print_output_header();

find_binaries("condor_ce_ping");
my $name = $options{u};
$name =~ s/:\d+$//;
my $cmd = "condor_ce_ping -pool '$options{u}' -name '$name' -table READ WRITE DAEMON";

my $output = `$cmd`;

if($? == 0) {
    print "OK\n";
    print "Output from $cmd:\n";
    print "$output\n";
}
else {
    # The message from globusrun is not generally helpful.  So we will
    # print it, but we'll also try a globus-url-copy and include that
    # output because it tends to have better error messages.
    print "CRITICAL\n";
    print "Output from $cmd\n";
    print "$output\n";

    # TODO Now run globus-url-copy
}

exit 0;
