#!/usr/bin/env perl

use strict;
use warnings;
use RSVMetric;

print_output_header();

my %options = process_command_line();

if(defined $ENV{OSG_LOCATION}) {
    monitor_old();
}
else {
    # TODO - something more interesting than a list of RPMs?
    print "OK\n";
    print "\n\nList of RPMs:\n" . `rpm -qa | sort`;
}

exit 0;


sub monitor_old {
    my $osg_version = "$ENV{OSG_LOCATION}/osg/bin/osg-version";

    if (! -x $osg_version) {
        print "CRITICAL\n";
        print "Can't find vdt-version!\n";
        dump_debug();
    }
    else {
        my $version_out = `$osg_version 2>&1`;
        if ($? == 0) {
            print "OK\n";
            print $version_out;
        } 
        else {
            print "CRITICAL\n";
            print $version_out;
            dump_debug();
        }
    }
}
