#!/usr/bin/python

import os
import re
import subprocess
import sys
import rsvprobe

class PefsonarSimpleProbe(rsvprobe.RSVProbe):
    """
    TODO - write description of the probe
    """

    def __init__(self):
        rsvprobe.RSVProbe.__init__(self)
	

def main():
    probe = PerfsonarSimpleProbe()
    return probe.run()

if __name__ == '__main__':
    sys.exit(main())
    
