#!/usr/bin/env perl

use strict;
use warnings;

# We assume we have the normal environment for a fork job here. It has
# $OSG_LOCATION but not $VDT_LOCATION

print "RSV BRIEF RESULTS:\n";

my $vdt_location = $ENV{OSG_LOCATION};
my $vdt_version = "$vdt_location/vdt/bin/vdt-version";

if (! -x $vdt_version) {
    print "CRITICAL\n";
    print "Can't find vdt-version!\n";
    dump_debug();
}
else {
    my $version_out = `$vdt_version -vdt-location $vdt_location 2>&1`;
    if ($? == 0) {
        print "OK\n";
        print $version_out;
    } 
    else {
        print "CRITICAL\n";
        print $version_out;
        dump_debug();
    }
}

exit 0;

sub dump_debug {
    print STDERR "vdt_location = $vdt_location\n";
    print STDERR `/usr/bin/env`;
    return;
}
